#!/usr/bin/env ruby

require 'rubygems'

require_relative 'load_path'
require 'bundler/setup'

require 'pry'

spec = Gem::Specification.load('rubygems-runtime.gemspec')

source_code_uri = spec.metadata['source_code_uri']
generator_url = "#{source_code_uri}/blob/master/#{File.basename($PROGRAM_NAME)}"

File.open('lib/rubygems/runtime/gem_extensions.rb', 'w') do |rb|
  rb.puts <<~RUBY
  # Generated by #{generator_url}
  module Rubygems
    module Runtime
      module GemExtensions
        @@win_platform = nil

        WIN_PATTERNS = #{Gem::WIN_PATTERNS.inspect}

        def ruby
          ::RbConfig.ruby
        end

        def target_rbconfig
          ::RbConfig::CONFIG
        end

        def path
          [default_dir]
        end

  RUBY

  platform_predicate_methods = Gem.methods.grep(/_platform\?$/)

  [
    :ruby_api_version,
    :extension_api_version,
    :default_dir,
    :location_of_caller,
    *platform_predicate_methods
  ].each_with_index do |method_name, index|
    method = Gem.method(method_name)

    unmodified_source = method.source

    modified_source = unmodified_source.
      sub('def self.', 'def ').
      gsub(/^/, '    ')

    if index > 0
      rb.puts
    end

    ruby_lib_dir = File.join(
      RbConfig::CONFIG['rubylibprefix'],
      RbConfig::CONFIG['ruby_version']
    )

    absolute_file, line = method.source_location

    file = absolute_file.delete_prefix(File.join(ruby_lib_dir, ''))

    rb.puts "      # Copied from Rubygems v#{Gem::VERSION} lib/#{file}:#{line}"

    rb.puts modified_source
  end

  rb.puts <<~RUBY
      end
    end
  end
  RUBY
end
