#!/usr/bin/env ruby

require 'rubygems'

require_relative 'load_path'
require 'bundler/setup'

require 'pry'

File.open('lib/rubygems/runtime/gem_extensions/generated.rb', 'w') do |rb|
  rb.puts <<~RUBY
  # Generated by #{$PROGRAM_NAME}
  module Gem
    WIN_PATTERNS = #{Gem::WIN_PATTERNS.inspect}
  RUBY

  platform_predicate_methods = Gem.methods.grep(/_platform\?$/)

  [
    :ruby_api_version,
    :extension_api_version,
    :default_dir,
    :location_of_caller,
    *platform_predicate_methods
  ].each do |method_name|
    method = Gem.method(method_name)

    rb.puts method.source
  end

  rb.puts "end"
end
